version: '3.8'

services:
  varnish:
    image: varnish:6.5
    ports:
      - 6081:80
    volumes:
      - ./docker/varnish/default.vcl:/etc/varnish/default.vcl
    depends_on:
      - app

  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
      target: base
    ports:
      - 8080:80
    volumes:
      - app:/var/www/html
    env_file:
      - .env

volumes:
  app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: :/System/Volumes/Data/${PWD}
