version: '3.8'

services:
  app:
    build:
      context: ./app
      target: base
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
    env_file:
      - ./app/.env
    depends_on:
      - api
      - minio

  api:
    build: ./api
    ports:
      - 8081:80
    volumes:
      - ./api:/var/www/html
    env_file:
      - ./api/.env
    depends_on:
      - db
      - minio

  db:
    image: mysql:5.7
    ports:
      - 33060:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - minio:/data
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=secretkey

volumes:
  db:
  minio:

# volumes:
#   app:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
#       device: :/System/Volumes/Data/${PWD}/app
