version: '3.8'

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
      target: base
    ports:
      - 8080:80
    volumes:
      - app:/var/www/html
    env_file:
      - .env

volumes:
  app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: :/System/Volumes/Data/${PWD}
