apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.105.230.252
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
