doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    server_version: '5.7'

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Api:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'Api\Entity'
        alias: Api

doctrine_migrations:
  migrations_paths:
    'DoctrineMigrations': '%kernel.project_dir%/migrations'

maker:
  root_namespace: 'Api'
