name: Build, test and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  IMAGE: app

jobs:
  docker:
    name: Build, test, and release the Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: $GCP_PROJECT_ID
          service_account_key: $GCP_SA_KEY

      - name: Register gcloud as a Docker credential helper
        run: gcloud --quiet auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          load: true
          context: .
          file: ./docker/app/Dockerfile
          tags: app
          cache-from: type=registry,ref=gcr.io/$GCP_PROJECT_ID/$IMAGE:latest
          cache-to: type=inline

      - name: Run PHPUnit tests
        run: docker run app ./vendor/bin/phpunit --verbose

      - name: Tag the Docker image with the Git SHA
        run: docker tag app gcr.io/$GCP_PROJECT_ID/$IMAGE:$GITHUB_SHA

      - name: Tag the Docker image with latest
        if: github.event_name != 'pull_request'
        run: docker tag app gcr.io/$GCP_PROJECT_ID/$IMAGE:latest

      - name: Publish the Docker image
        run: docker push gcr.io/$PROJECT_ID/$IMAGE
