name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/web/Dockerfile
          push: true
          tags: |
            ghcr.io/jack97/its-always-sunny-in-filly:sha-${{ github.sha }}

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Run the tests
        run: |
          docker run \
            ghcr.io/jack97/its-always-sunny-in-filly:sha-${{ github.sha }} \
            ./vendor/bin/phpunit
