name: Test and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: Build, test, and release the Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          load: true
          context: .
          file: ./docker/app/Dockerfile
          tags: app
          cache-from: type=registry,ref=ghcr.io/jack97/its-always-sunny-in-filly:latest
          cache-to: type=inline

      - name: Run PHPUnit tests
        run: docker run app ./vendor/bin/phpunit --verbose

      - name: Release the Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker tag app ghcr.io/jack97/its-always-sunny-in-filly:latest
          docker push ghcr.io/jack97/its-always-sunny-in-filly
