name: Build, test and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/app

jobs:
  docker:
    name: Build, test, and release the Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Register gcloud as a Docker credential helper
        run: gcloud --quiet auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          load: true
          context: .
          file: ./docker/app/Dockerfile
          tags: app
          cache-from: type=registry,ref=${{ env.IMAGE }}:latest
          cache-to: type=inline

      - name: Run PHPUnit tests
        run: docker run app ./vendor/bin/phpunit --verbose

      - name: Tag the Docker image with the Git SHA
        run: docker tag app $IMAGE:$GITHUB_SHA

      - name: Tag the Docker image with latest
        if: github.event_name != 'pull_request'
        run: docker tag app $IMAGE:latest

      - name: Publish the Docker image
        run: docker push $IMAGE
