name: Build, test, and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/app

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Login to Google Cloud Container Registry
        run: gcloud --quiet auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          load: true
          context: .
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:latest
          cache-to: type=inline

      - name: Run PHPUnit tests
        run: docker run $IMAGE ./vendor/bin/phpunit --verbose

      - name: Publish the Docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push $IMAGE
